### ISSUE TITLE
LFG fails when organizer on same realm

### ISSUE THREAD

**Issue by Crosbyg** [gentoomaniac/QuickLink#2]
Thanks for this.
Quick bug-fix suggestion, and a feature-request.

Bug:
When using LFD, if organizer is on my same realm, QuickLink fails.
What is happening is LFG.lua line 14 is calling ShowUrlFrame() with no server arg.  Then in ShowUrlFrame() it is attempting to get servername from name, but instead is populating server with the same value as name b/c there is no "-".

Working fix, insert the following into core.lua, line #88:
if server == name then server = GetRealmName() end
(this works b/c servers are reserved names, so it would never be the case there is a player Stormrage-Stormrage, for example)

FWIW, IMHO, there is a better fix, which is to correct this in lfg.lua, prior to calling ShowUrlFrame(), and then remove the redundant checks for empty server that cascade through.

Cool, thanks,

And a feature request / suggestion.  Right-clicking is tedious if I want multiple links.  Just do one menu item that spawns a dialog with multiple text boxes, one per link.  I can copy/paste from there! maybe a config option?

Thanks!

**Comment by gentoomaniac** [comment]
Thanks for the great feedback!

I totally agree on your feature request aswell. Also in that scenario it should be easy to add a keybinding to open the dialog for the targeted user.

Can't commit to a timeliness for implementation but will def have a look into it.

**Comment by gentoomaniac** [comment]
This should be fixed in the next build
