### ISSUE TITLE
Config update

### ISSUE THREAD

**Issue by GravetoGeek** [gentoomaniac/QuickLink#3]
It is necessary to update addon settings because AskMtRobot does not manage characters. I tried to add a guild placeholder for guild link in wowprogress But I failed.

'-- default config settings
local QuickLink_defaultPages = {
    { name = "Armory", url = "http://{REGION}.battle.net/wow/{LANGUAGE}/character/{REALM}/{NAME}/advanced", enabled = true },
    { name = "WowTrack", url = "https://wowtrack.org/characters/{REGION}/{REALM}/{NAME}", enabled = true },
    { name = "Guildox", url = "http://guildox.com/toon/{REGION}/{REALM}/{NAME}", enabled = true },
    { name = "WOW Progress", url = "http://www.wowprogress.com/character/{REGION}/{REALM}/{NAME}", enabled = true },
	{ name = "WarcraftParser", url = "https://www.warcraftparser.com/character/{REGION}/{REALM}/{NAME}/", enabled = true},
	{ name = "Add Char Guildox", url = "http://guildox.com/add/toon?realm=&toon={NAME}", enabled = true},
	{ name = "Add char Wow Progress", url = "https://www.wowprogress.com/u_search?name={NAME}&realm={REALM}&area={REGION}&obj_type=char", enabled = true},

}'

**Comment by gentoomaniac** [comment]
AMR link should is updated in the next build
